modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="god_blocks"
version="1.0.0"
displayName="god blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joshu, MCreator"

[[dependencies.god_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




